//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iot_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders_Track
    {
        public int Id_Track { get; set; }
        public string Id_Order { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_Shipper { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual User User { get; set; }
    }
}
