//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Iot_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Orders_Item = new HashSet<Orders_Item>();
            this.Orders_Track = new HashSet<Orders_Track>();
        }
    
        public string Id_Order { get; set; }
        public Nullable<int> Id_Users { get; set; }
        public Nullable<int> Id_Shop { get; set; }
        public Nullable<double> Delivery { get; set; }
        public string Payment { get; set; }
        public Nullable<System.DateTime> Create_Orders { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
        public Nullable<int> Id_Address { get; set; }
        public Nullable<double> Total_Order { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Item> Orders_Item { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_Track> Orders_Track { get; set; }
    }
}
